### ISSUE TITLE
IconCls is not working.

### ISSUE THREAD

**Issue by sreeram79** [jseppi/angular-dropdowns#38]
Hi,

Please could you add the below line of code to use the iconCls in the templates DropdownSelectItem and dropdownMenuItem. or if you think the code needs to be added in the controller function you need to provide more options in the template with a loop condition to populate various element classes.

'<i class="{{ dropdownMenuItem[\'iconCls\'] }}"> </i>',

ex :-1:
$templateCache.put('ngDropdowns/templates/dropdownMenuItem.html', [
    '<li ng-class="{divider: dropdownMenuItem.divider | iconcls: dropdow}">',
      '<a href="" class="dropdown-item"',
      ' ng-if="!dropdownMenuItem.divider"',
      ' ng-href="{{dropdownMenuItem.href}}"',
      ' ng-click="selectItem()">',
        '{{dropdownMenuItem[dropdownItemLabel]}}',
        '<i class="{{ dropdownMenuItem[\'iconCls\'] }}"> </i>',
      '</a>',
    '</li>'
  ].join(''));
Thanks
Sreeram

**Comment by jseppi** [comment]
Hi Sreeram,
`iconCls` was never meant to be one of the 'core' features, just an example that the configuration object could be anything. Since all the templates can be overwritten, I think it would be best to just use a custom template instead of making this a core feature of the library (since I think most people will not use icons in their menu items).
I apologize that my intentions were not clear and will iconCls from from the example code.

**Comment by enesaltinkaya** [comment]
> since I think most people will not use icons in their menu items

Rich.
