### ISSUE TITLE
Feature Requests - Disabling and Classes

### ISSUE THREAD

**Issue by kmbicatl** [jseppi/angular-dropdowns#53]
Hi,

It would be nice if we can have option disabling feature. So that the option should not get highlighted nor selectable. If such feature is available, I would like to use it for Header option something equivalent like <optgroup> in a select box.

Also while declaring options, if you can provide addtional attributes to input class or style that would be a great help.

**Comment by jseppi** [comment]
There is a way to make headers or divider labels currently. In the README see these examples:

```js
...
        {
            // Any option with divider set to true will be a divider
            // in the menu and cannot be selected.
            divider: true
        },
        {
            // Any divider option with a 'text' property will
            // behave similarly to a divider and cannot be selected.
            divider: true,
            text: 'divider label'
        }
...
```

Also, any class specified on the original element will be present on the dropdown. The example below will have `my-class my-other-class` on the dropdown element:

```html
    <div class="my-class my-other-class"
        dropdown-select="ddSelectOptions"
        dropdown-model="ddSelectSelected"
        dropdown-item-label="text" >
    </div>
```

In general, it is very helpful to project maintainers if you use descriptive issue titles instead of generic ones. This helps us quickly glance over our lists of issues and know what they are about. Thanks.

**Comment by kmbicatl** [comment]
Thank you james. This helped me a lot and I will do more specific about my issue titles next time onwards.

Thanks again!

**Comment by jseppi** [comment]
:+1:
